### ISSUE TITLE
Move govpp.conf to /etc/govpp/govpp.conf

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/cmd-forwarder-vppagent#7]
From Denis: https://github.com/networkservicemesh/cmd-forwarder-vppagent/pull/6#discussion_r385029426

"Let's move govpp.conf to /etc/govpp/govpp.conf to avoid problems with vpp-agent v3.0.1 starting."

**Comment by denis-tingajkin** [comment]
Example: https://github.com/networkservicemesh/networkservicemesh/blob/b988ac77297c049dbf52d5bcd3df6be76cb7236e/build/Dockerfile.vppagent-forwarder#L8
