### ISSUE TITLE
[Question] Should we push docker image into networkservicemeshci on each merge to origin/master?

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/cmd-forwarder-vppagent#88]
## Problem statement

We need to be able to run our cmd applications in integration-%v repositories.

## Potential solution

Push docker cmd images to `networkservicemeshci` docker hub on each merging to origin/master

**Comment by edwarnicke** [comment]
It might be good to explore using [Github packages](https://github.com/features/packages).

**Comment by denis-tingajkin** [comment]
Thanks this question is resolved :)
